include(${CMAKE_ROOT}/Modules/FindPkgConfig.cmake)

#if(PKG_CONFIG_FOUND)
#    set(FOUND_TEXT "Found")
#else()
#    set(FOUND_TEXT "Not found")
#endif()
#message(STATUS "pkg-config: ${FOUND_TEXT}")
#message(STATUS "  binary  : ${PKG_CONFIG_EXECUTABLE}")
#message(STATUS "  version : ${PKG_CONFIG_VERSION_STRING}")
